version: '3'
services:
  todo-api:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    command: ['pm2-runtime', 'ecosystem.config.js']
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
