version: '3'
services:
  todo-api:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
    working_dir: /app
    environment:
      - NODE_ENV=staging
    depends_on:
      - redis

  worker:
    build: .
    command: node queue/worker.js
    volumes:
      - ./data:/app/data
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - '16686:16686'
      - '4318:4318'

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-api
